name: dClimate Precipitation - US
description: Request a us location and date - lat, lon, unix timestamp - to get historical precipitation data for that day in mm.

node_identifier: DCPUS

platforms:
  - GCP Functions

data_sources:
  - name: dClimate
    url: https://api.dclimate.net/

parameters:
  - lat
  - lon
  - date
